name: Tool Installer
description: Dispatches to specific tool installers
inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Dispatch to tool installer
      uses: ./.github/actions/tool-installer/tools/${{ inputs.tool }}
      with:
        version: ${{ inputs.version }}
