name: Tool Installer
description: Dispatch to tool installers
inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3

    # - name: Install Python
    #   if: ${{ inputs.tool == 'python' }}
    #   uses: .github/actions/tool-installer/tools/python.yml
    #   with:
    #     version: ${{ inputs.version }}

    - name: Install Python2
      if: ${{ inputs.tool == 'python' }}
      uses: .github/actions/tool-installer/tools/python
      with:
        version: ${{ inputs.version }}

    # - name: Install Node.js
    #   if: ${{ inputs.tool == 'node' }}
    #   uses: ./.github/actions/tool-installer/tools/node/action.yml
    #   with:
    #     version: ${{ inputs.version }}

    # - name: Install MATLAB
    #   if: ${{ inputs.tool == 'matlab' }}
    #   uses: ./.github/actions/tool-installer/tools/matlab/action.yml
    #   with:
    #     version: ${{ inputs.version }}
