name: Tool Installer
description: Installs a tool with optional version

inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: composite
  steps:
    - run: ./.github\actions\tool-installer\install.sh
      shell: bash
