name: Tool Installer
description: Installs a tool with optional version

inputs:
  tool:
    required: true
  version:
    required: false

runs:
  using: composite
  steps:
    - run: |
        chmod +x ./.github/actions/tool-installer/install.sh
        ./.github/actions/tool-installer/install.sh "${{ inputs.tool }}" "${{ inputs.version }}"
      shell: bash
